### ISSUE TITLE
Log rotation limited by maximum timeout length

### ISSUE THREAD

**Issue by reedog117** [hapijs/good-file#61] opened 2015-05-28 19:11 UTC
When researching #59 and #60 I found the maximum timeout length is limited to 2147483647 ms. Implementing timeout chaining would allow for longer timeouts so that monthly and yearly logfile rotation works properly.

**Comment by arb** [comment] 2015-05-28 19:47
My concern with this is the potential to leave a lot of un-managed `setTimeouts` floating around as you have to chain more and more of them together.

**Comment by reedog117** [comment] 2015-05-29 07:51
I have a version that uses the ```long-timeout``` module to implement timeouts longer than 2147483647 ms, but I'm having trouble rewriting the test ```rotates logs on the specified interval``` so that it passes.

In the original version, Math.min was overloaded so that it would trigger a rotate in 100ms even though it's set to daily. Not sure what to do in this case since I no longer use min.

```js
internals.setUpRotate = function (reporter, period) {

    var now = Moment.utc();

    period = period.toLowerCase();
    now.endOf(internals.timeMap[period]);
    var timeout = now.valueOf() - Date.now();

    reporter._state.timeout = Lt.setTimeout(function () {

        internals.rotate(reporter, period);
    }, timeout);

};
```

**Comment by reedog117** [comment] 2015-05-29 08:01
Came up with a hokey solution, but it works! Submitting a pull request now...

```js
    timeout = Math.min(timeout, timeout); // for test compatibility
```

**Comment by Marsup** [comment] 2015-06-13 11:07
@arb Why is it an enhancement ? Looks a lot like a bug to me.

**Comment by arb** [comment] 2015-06-13 16:13
Because as it was, it would just chop of the time to the max time `setTimout` could support. This was the documented behavior. Changing it so it now works would be considered an enhancement.

**Comment by Marsup** [comment] 2015-06-13 16:34
IIRC, overflow on setTimeout is strictly equivalent to setting it to 0, so it's immediate, probably the cause of the IO exception on #63.

**Comment by arb** [comment] 2015-06-13 18:07
This code allows using timeout beyond the capabilities of existing good-file, so it's an enhancement.

**Comment by arb** [comment] 2015-06-15 17:33
Closed via https://github.com/hapijs/good-file/pull/62

**Closed by arb** 2015-06-15 17:33 UTC
Labels: enhancement, request
