### ISSUE TITLE
[1] value must be a string [2] path is required

### ISSUE THREAD

**Issue by brandonramirez** [hapijs/good-file#56] opened 2015-04-23 01:47 UTC
When `good` instantiates a reporter instance in monitor.js, it passes in `(events, config)`.  However, the constructor for `GoodFile` expects `(config, events)`, which is backwards.  This causes the following validation error on good-file/lib/index.js line 72:

    Error: {
      "ops": "*",
      "path" [1]: -- missing --,
      "value" [2]: -- missing --
    }

My reporters array looks like this:

    {
        reporters: [{
          reporter: require('good-file'),
          events: { ops: '*' },
          config: { path: nconf.get('log:root'), prefix: 'ops', rotate: 'daily' }
        }, {
          reporter: require('good-file'),
          events: { request: '*' },
          config: { path: nconf.get('log:root'), prefix: 'request', rotate: 'daily' }
        }]
      }

I just did a fresh update of `joi`, `good`, and `good-file`.

Swapping the parameters in the constructor solves this problem, so this:

    module.exports = internals.GoodFile = function (config, events) {

becomes:

    module.exports = internals.GoodFile = function (events, config) {

**Comment by arb** [comment] 2015-04-23 13:16
Duplicate of https://github.com/hapijs/good-file/issues/57

**Closed by arb** 2015-04-23 13:16 UTC
