### ISSUE TITLE
Problem with log rotation 'monthly'

### ISSUE THREAD

**Issue by fhemberger** [hapijs/good-file#63] opened 2015-06-13 10:45 UTC
I added good-file as reporter to a hapi v8 project with the following configuration:

```
reporters: [
    {
        reporter: require('good-file'),
        events: { response: '*' },
        config: {
            path   : './log/',
            prefix : 'access',
            rotate : 'monthly'
        }
    }
]
```

As soon as I start the server, it creates 8986 zero-byte log files and the server crashes (ENFILE: file table overflow). Using 'daily' as rotate setting seems to work fine.

**Comment by Marsup** [comment] 2015-06-13 11:04
Related to #62.

**Comment by Marsup** [comment] 2015-06-13 11:05
And duplicate of #61.

**Closed by Marsup** 2015-06-13 11:05 UTC
